// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: policy.proto

package policypb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_DENY        Decision = 2
	Decision_DECISION_WARN        Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
		3: "DECISION_WARN",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
		"DECISION_WARN":        3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

type EvaluateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input is the data to evaluate against policies
	Input *structpb.Struct `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Policies to evaluate (empty = all applicable)
	PolicyNames []string `protobuf:"bytes,2,rep,name=policy_names,json=policyNames,proto3" json:"policy_names,omitempty"`
	// Namespace scope
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Options for evaluation
	Options       *EvaluateOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *EvaluateRequest) GetPolicyNames() []string {
	if x != nil {
		return x.PolicyNames
	}
	return nil
}

func (x *EvaluateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EvaluateRequest) GetOptions() *EvaluateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type EvaluateOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Return full trace for debugging
	Trace bool `protobuf:"varint,1,opt,name=trace,proto3" json:"trace,omitempty"`
	// Return all results including passes
	IncludePassed bool `protobuf:"varint,2,opt,name=include_passed,json=includePassed,proto3" json:"include_passed,omitempty"`
	// Strict mode fails on any warning
	Strict bool `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	// Instrument for performance metrics
	Instrument bool `protobuf:"varint,4,opt,name=instrument,proto3" json:"instrument,omitempty"`
	// Override dry_run setting
	DryRun        *bool `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3,oneof" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateOptions) Reset() {
	*x = EvaluateOptions{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateOptions) ProtoMessage() {}

func (x *EvaluateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateOptions.ProtoReflect.Descriptor instead.
func (*EvaluateOptions) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateOptions) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *EvaluateOptions) GetIncludePassed() bool {
	if x != nil {
		return x.IncludePassed
	}
	return false
}

func (x *EvaluateOptions) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *EvaluateOptions) GetInstrument() bool {
	if x != nil {
		return x.Instrument
	}
	return false
}

func (x *EvaluateOptions) GetDryRun() bool {
	if x != nil && x.DryRun != nil {
		return *x.DryRun
	}
	return false
}

type EvaluateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall decision
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=garmr.policy.v1.Decision" json:"decision,omitempty"`
	// Individual rule results
	Results []*RuleResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// Metrics if instrumentation enabled
	Metrics *Metrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Trace if requested
	Trace         []*TraceEvent `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *EvaluateResponse) GetResults() []*RuleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EvaluateResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EvaluateResponse) GetTrace() []*TraceEvent {
	if x != nil {
		return x.Trace
	}
	return nil
}

type RuleResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyName      string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyNamespace string                 `protobuf:"bytes,2,opt,name=policy_namespace,json=policyNamespace,proto3" json:"policy_namespace,omitempty"`
	RuleId          string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleDescription string                 `protobuf:"bytes,4,opt,name=rule_description,json=ruleDescription,proto3" json:"rule_description,omitempty"`
	Severity        Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=garmr.policy.v1.Severity" json:"severity,omitempty"`
	Passed          bool                   `protobuf:"varint,6,opt,name=passed,proto3" json:"passed,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Bindings        []*Binding             `protobuf:"bytes,8,rep,name=bindings,proto3" json:"bindings,omitempty"` // Variable bindings from match
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleResult) Reset() {
	*x = RuleResult{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResult) ProtoMessage() {}

func (x *RuleResult) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResult.ProtoReflect.Descriptor instead.
func (*RuleResult) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *RuleResult) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *RuleResult) GetPolicyNamespace() string {
	if x != nil {
		return x.PolicyNamespace
	}
	return ""
}

func (x *RuleResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleResult) GetRuleDescription() string {
	if x != nil {
		return x.RuleDescription
	}
	return ""
}

func (x *RuleResult) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *RuleResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RuleResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuleResult) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Binding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Binding) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EvaluationTimeNs  int64                  `protobuf:"varint,1,opt,name=evaluation_time_ns,json=evaluationTimeNs,proto3" json:"evaluation_time_ns,omitempty"`
	PoliciesEvaluated int32                  `protobuf:"varint,2,opt,name=policies_evaluated,json=policiesEvaluated,proto3" json:"policies_evaluated,omitempty"`
	RulesEvaluated    int32                  `protobuf:"varint,3,opt,name=rules_evaluated,json=rulesEvaluated,proto3" json:"rules_evaluated,omitempty"`
	CompileTimeNs     int64                  `protobuf:"varint,4,opt,name=compile_time_ns,json=compileTimeNs,proto3" json:"compile_time_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{5}
}

func (x *Metrics) GetEvaluationTimeNs() int64 {
	if x != nil {
		return x.EvaluationTimeNs
	}
	return 0
}

func (x *Metrics) GetPoliciesEvaluated() int32 {
	if x != nil {
		return x.PoliciesEvaluated
	}
	return 0
}

func (x *Metrics) GetRulesEvaluated() int32 {
	if x != nil {
		return x.RulesEvaluated
	}
	return 0
}

func (x *Metrics) GetCompileTimeNs() int64 {
	if x != nil {
		return x.CompileTimeNs
	}
	return 0
}

type TraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Locals        *structpb.Struct       `protobuf:"bytes,5,opt,name=locals,proto3" json:"locals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{6}
}

func (x *TraceEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TraceEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TraceEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TraceEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TraceEvent) GetLocals() *structpb.Struct {
	if x != nil {
		return x.Locals
	}
	return nil
}

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy content in CUE format
	Policy string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// Filename for error reporting
	Filename      string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *ValidateRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []*ValidationError     `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateResponse) GetWarnings() []*ValidationError {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{9}
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{10}
}

func (x *Position) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicySource        `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{11}
}

func (x *CompileRequest) GetPolicies() []*PolicySource {
	if x != nil {
		return x.Policies
	}
	return nil
}

type PolicySource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // CUE source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySource) Reset() {
	*x = PolicySource{}
	mi := &file_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySource) ProtoMessage() {}

func (x *PolicySource) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySource.ProtoReflect.Descriptor instead.
func (*PolicySource) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{12}
}

func (x *PolicySource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicySource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicySource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Bundle        []byte                 `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"` // Compiled bundle for caching
	BundleHash    string                 `protobuf:"bytes,4,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{13}
}

func (x *CompileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompileResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CompileResponse) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *CompileResponse) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // Empty = all namespaces
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{14}
}

func (x *ListPoliciesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListPoliciesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyInfo          `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{15}
}

func (x *ListPoliciesResponse) GetPolicies() []*PolicyInfo {
	if x != nil {
		return x.Policies
	}
	return nil
}

type PolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RuleCount     int32                  `protobuf:"varint,4,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	LoadedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyInfo) Reset() {
	*x = PolicyInfo{}
	mi := &file_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyInfo) ProtoMessage() {}

func (x *PolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyInfo.ProtoReflect.Descriptor instead.
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{16}
}

func (x *PolicyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicyInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PolicyInfo) GetRuleCount() int32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

func (x *PolicyInfo) GetLoadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoadedAt
	}
	return nil
}

func (x *PolicyInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{17}
}

func (x *GetPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // CUE source
	Info          *PolicyInfo            `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{18}
}

func (x *GetPolicyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPolicyResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPolicyResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetPolicyResponse) GetInfo() *PolicyInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PutPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ValidateOnly  bool                   `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPolicyRequest) Reset() {
	*x = PutPolicyRequest{}
	mi := &file_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPolicyRequest) ProtoMessage() {}

func (x *PutPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPolicyRequest.ProtoReflect.Descriptor instead.
func (*PutPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{19}
}

func (x *PutPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutPolicyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PutPolicyRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

type PutPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Info          *PolicyInfo            `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPolicyResponse) Reset() {
	*x = PutPolicyResponse{}
	mi := &file_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPolicyResponse) ProtoMessage() {}

func (x *PutPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPolicyResponse.ProtoReflect.Descriptor instead.
func (*PutPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{20}
}

func (x *PutPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutPolicyResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *PutPolicyResponse) GetInfo() *PolicyInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_policy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeletePolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_policy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePolicyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ReloadPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPoliciesRequest) Reset() {
	*x = ReloadPoliciesRequest{}
	mi := &file_policy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPoliciesRequest) ProtoMessage() {}

func (x *ReloadPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ReloadPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{23}
}

func (x *ReloadPoliciesRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ReloadPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        int32                  `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPoliciesResponse) Reset() {
	*x = ReloadPoliciesResponse{}
	mi := &file_policy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPoliciesResponse) ProtoMessage() {}

func (x *ReloadPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ReloadPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{24}
}

func (x *ReloadPoliciesResponse) GetLoaded() int32 {
	if x != nil {
		return x.Loaded
	}
	return 0
}

func (x *ReloadPoliciesResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ReloadPoliciesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type PutDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataRequest) Reset() {
	*x = PutDataRequest{}
	mi := &file_policy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataRequest) ProtoMessage() {}

func (x *PutDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataRequest.ProtoReflect.Descriptor instead.
func (*PutDataRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{25}
}

func (x *PutDataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutDataRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataResponse) Reset() {
	*x = PutDataResponse{}
	mi := &file_policy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataResponse) ProtoMessage() {}

func (x *PutDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataResponse.ProtoReflect.Descriptor instead.
func (*PutDataResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{26}
}

func (x *PutDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_policy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{27}
}

func (x *GetDataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_policy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{28}
}

func (x *GetDataResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_policy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteDataRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_policy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteDataResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_policy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{31}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_policy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{32}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptime() *timestamppb.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_policy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{33}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Checks        map[string]bool        `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Individual readiness checks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_policy_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{34}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetChecks() map[string]bool {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x0fgarmr.policy.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n" +
	"\x0fEvaluateRequest\x12-\n" +
	"\x05input\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05input\x12!\n" +
	"\fpolicy_names\x18\x02 \x03(\tR\vpolicyNames\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12:\n" +
	"\aoptions\x18\x04 \x01(\v2 .garmr.policy.v1.EvaluateOptionsR\aoptions\"\xb0\x01\n" +
	"\x0fEvaluateOptions\x12\x14\n" +
	"\x05trace\x18\x01 \x01(\bR\x05trace\x12%\n" +
	"\x0einclude_passed\x18\x02 \x01(\bR\rincludePassed\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict\x12\x1e\n" +
	"\n" +
	"instrument\x18\x04 \x01(\bR\n" +
	"instrument\x12\x1c\n" +
	"\adry_run\x18\x05 \x01(\bH\x00R\x06dryRun\x88\x01\x01B\n" +
	"\n" +
	"\b_dry_run\"\xe7\x01\n" +
	"\x10EvaluateResponse\x125\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x19.garmr.policy.v1.DecisionR\bdecision\x125\n" +
	"\aresults\x18\x02 \x03(\v2\x1b.garmr.policy.v1.RuleResultR\aresults\x122\n" +
	"\ametrics\x18\x03 \x01(\v2\x18.garmr.policy.v1.MetricsR\ametrics\x121\n" +
	"\x05trace\x18\x04 \x03(\v2\x1b.garmr.policy.v1.TraceEventR\x05trace\"\xbb\x02\n" +
	"\n" +
	"RuleResult\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12)\n" +
	"\x10policy_namespace\x18\x02 \x01(\tR\x0fpolicyNamespace\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12)\n" +
	"\x10rule_description\x18\x04 \x01(\tR\x0fruleDescription\x125\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x19.garmr.policy.v1.SeverityR\bseverity\x12\x16\n" +
	"\x06passed\x18\x06 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x124\n" +
	"\bbindings\x18\b \x03(\v2\x18.garmr.policy.v1.BindingR\bbindings\"K\n" +
	"\aBinding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\xb7\x01\n" +
	"\aMetrics\x12,\n" +
	"\x12evaluation_time_ns\x18\x01 \x01(\x03R\x10evaluationTimeNs\x12-\n" +
	"\x12policies_evaluated\x18\x02 \x01(\x05R\x11policiesEvaluated\x12'\n" +
	"\x0frules_evaluated\x18\x03 \x01(\x05R\x0erulesEvaluated\x12&\n" +
	"\x0fcompile_time_ns\x18\x04 \x01(\x03R\rcompileTimeNs\"\xcb\x01\n" +
	"\n" +
	"TraceEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12/\n" +
	"\x06locals\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06locals\"E\n" +
	"\x0fValidateRequest\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\xa0\x01\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x128\n" +
	"\x06errors\x18\x02 \x03(\v2 .garmr.policy.v1.ValidationErrorR\x06errors\x12<\n" +
	"\bwarnings\x18\x03 \x03(\v2 .garmr.policy.v1.ValidationErrorR\bwarnings\"v\n" +
	"\x0fValidationError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\bposition\x18\x02 \x01(\v2\x19.garmr.policy.v1.PositionR\bposition\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"R\n" +
	"\bPosition\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"K\n" +
	"\x0eCompileRequest\x129\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1d.garmr.policy.v1.PolicySourceR\bpolicies\"Z\n" +
	"\fPolicySource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x9e\x01\n" +
	"\x0fCompileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x06errors\x18\x02 \x03(\v2 .garmr.policy.v1.ValidationErrorR\x06errors\x12\x16\n" +
	"\x06bundle\x18\x03 \x01(\fR\x06bundle\x12\x1f\n" +
	"\vbundle_hash\x18\x04 \x01(\tR\n" +
	"bundleHash\"\xb8\x01\n" +
	"\x13ListPoliciesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12H\n" +
	"\x06labels\x18\x02 \x03(\v20.garmr.policy.v1.ListPoliciesRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x14ListPoliciesResponse\x127\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1b.garmr.policy.v1.PolicyInfoR\bpolicies\"\xa6\x02\n" +
	"\n" +
	"PolicyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12?\n" +
	"\x06labels\x18\x03 \x03(\v2'.garmr.policy.v1.PolicyInfo.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x04 \x01(\x05R\truleCount\x127\n" +
	"\tloaded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bloadedAt\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x10GetPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x90\x01\n" +
	"\x11GetPolicyResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12/\n" +
	"\x04info\x18\x04 \x01(\v2\x1b.garmr.policy.v1.PolicyInfoR\x04info\"\x83\x01\n" +
	"\x10PutPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\"\x98\x01\n" +
	"\x11PutPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x06errors\x18\x02 \x03(\v2 .garmr.policy.v1.ValidationErrorR\x06errors\x12/\n" +
	"\x04info\x18\x03 \x01(\v2\x1b.garmr.policy.v1.PolicyInfoR\x04info\"G\n" +
	"\x13DeletePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"0\n" +
	"\x14DeletePolicyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"-\n" +
	"\x15ReloadPoliciesRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"`\n" +
	"\x16ReloadPoliciesResponse\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\x05R\x06loaded\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"Q\n" +
	"\x0ePutDataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"+\n" +
	"\x0fPutDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x0eGetDataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\x0fGetDataResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"'\n" +
	"\x11DeleteDataRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x12DeleteDataResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x0f\n" +
	"\rHealthRequest\"x\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\x06uptime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\"\x0e\n" +
	"\fReadyRequest\"\xa4\x01\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12B\n" +
	"\x06checks\x18\x02 \x03(\v2*.garmr.policy.v1.ReadyResponse.ChecksEntryR\x06checks\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*^\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02\x12\x11\n" +
	"\rDECISION_WARN\x10\x03*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x052\xa4\x03\n" +
	"\rPolicyService\x12h\n" +
	"\bEvaluate\x12 .garmr.policy.v1.EvaluateRequest\x1a!.garmr.policy.v1.EvaluateResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/evaluate\x12Y\n" +
	"\x0eEvaluateStream\x12 .garmr.policy.v1.EvaluateRequest\x1a!.garmr.policy.v1.EvaluateResponse(\x010\x01\x12h\n" +
	"\bValidate\x12 .garmr.policy.v1.ValidateRequest\x1a!.garmr.policy.v1.ValidateResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/validate\x12d\n" +
	"\aCompile\x12\x1f.garmr.policy.v1.CompileRequest\x1a .garmr.policy.v1.CompileResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/compile2\x90\x05\n" +
	"\x17PolicyManagementService\x12q\n" +
	"\fListPolicies\x12$.garmr.policy.v1.ListPoliciesRequest\x1a%.garmr.policy.v1.ListPoliciesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/policies\x12{\n" +
	"\tGetPolicy\x12!.garmr.policy.v1.GetPolicyRequest\x1a\".garmr.policy.v1.GetPolicyResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/policies/{namespace}/{name}\x12~\n" +
	"\tPutPolicy\x12!.garmr.policy.v1.PutPolicyRequest\x1a\".garmr.policy.v1.PutPolicyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/policies/{namespace}/{name}\x12\x84\x01\n" +
	"\fDeletePolicy\x12$.garmr.policy.v1.DeletePolicyRequest\x1a%.garmr.policy.v1.DeletePolicyResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/policies/{namespace}/{name}\x12~\n" +
	"\x0eReloadPolicies\x12&.garmr.policy.v1.ReloadPoliciesRequest\x1a'.garmr.policy.v1.ReloadPoliciesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/v1/policies:reload2\xda\x02\n" +
	"\vDataService\x12n\n" +
	"\aPutData\x12\x1f.garmr.policy.v1.PutDataRequest\x1a .garmr.policy.v1.PutDataResponse\" \x82\xd3\xe4\x93\x02\x1a:\x04data\x1a\x12/v1/data/{path=**}\x12h\n" +
	"\aGetData\x12\x1f.garmr.policy.v1.GetDataRequest\x1a .garmr.policy.v1.GetDataResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/data/{path=**}\x12q\n" +
	"\n" +
	"DeleteData\x12\".garmr.policy.v1.DeleteDataRequest\x1a#.garmr.policy.v1.DeleteDataResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/data/{path=**}2\xc3\x01\n" +
	"\rHealthService\x12Z\n" +
	"\x06Health\x12\x1e.garmr.policy.v1.HealthRequest\x1a\x1f.garmr.policy.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12V\n" +
	"\x05Ready\x12\x1d.garmr.policy.v1.ReadyRequest\x1a\x1e.garmr.policy.v1.ReadyResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/readyB0Z.github.com/infrashift/garmr/api/proto;policypbb\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_policy_proto_goTypes = []any{
	(Decision)(0),                  // 0: garmr.policy.v1.Decision
	(Severity)(0),                  // 1: garmr.policy.v1.Severity
	(*EvaluateRequest)(nil),        // 2: garmr.policy.v1.EvaluateRequest
	(*EvaluateOptions)(nil),        // 3: garmr.policy.v1.EvaluateOptions
	(*EvaluateResponse)(nil),       // 4: garmr.policy.v1.EvaluateResponse
	(*RuleResult)(nil),             // 5: garmr.policy.v1.RuleResult
	(*Binding)(nil),                // 6: garmr.policy.v1.Binding
	(*Metrics)(nil),                // 7: garmr.policy.v1.Metrics
	(*TraceEvent)(nil),             // 8: garmr.policy.v1.TraceEvent
	(*ValidateRequest)(nil),        // 9: garmr.policy.v1.ValidateRequest
	(*ValidateResponse)(nil),       // 10: garmr.policy.v1.ValidateResponse
	(*ValidationError)(nil),        // 11: garmr.policy.v1.ValidationError
	(*Position)(nil),               // 12: garmr.policy.v1.Position
	(*CompileRequest)(nil),         // 13: garmr.policy.v1.CompileRequest
	(*PolicySource)(nil),           // 14: garmr.policy.v1.PolicySource
	(*CompileResponse)(nil),        // 15: garmr.policy.v1.CompileResponse
	(*ListPoliciesRequest)(nil),    // 16: garmr.policy.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),   // 17: garmr.policy.v1.ListPoliciesResponse
	(*PolicyInfo)(nil),             // 18: garmr.policy.v1.PolicyInfo
	(*GetPolicyRequest)(nil),       // 19: garmr.policy.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),      // 20: garmr.policy.v1.GetPolicyResponse
	(*PutPolicyRequest)(nil),       // 21: garmr.policy.v1.PutPolicyRequest
	(*PutPolicyResponse)(nil),      // 22: garmr.policy.v1.PutPolicyResponse
	(*DeletePolicyRequest)(nil),    // 23: garmr.policy.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),   // 24: garmr.policy.v1.DeletePolicyResponse
	(*ReloadPoliciesRequest)(nil),  // 25: garmr.policy.v1.ReloadPoliciesRequest
	(*ReloadPoliciesResponse)(nil), // 26: garmr.policy.v1.ReloadPoliciesResponse
	(*PutDataRequest)(nil),         // 27: garmr.policy.v1.PutDataRequest
	(*PutDataResponse)(nil),        // 28: garmr.policy.v1.PutDataResponse
	(*GetDataRequest)(nil),         // 29: garmr.policy.v1.GetDataRequest
	(*GetDataResponse)(nil),        // 30: garmr.policy.v1.GetDataResponse
	(*DeleteDataRequest)(nil),      // 31: garmr.policy.v1.DeleteDataRequest
	(*DeleteDataResponse)(nil),     // 32: garmr.policy.v1.DeleteDataResponse
	(*HealthRequest)(nil),          // 33: garmr.policy.v1.HealthRequest
	(*HealthResponse)(nil),         // 34: garmr.policy.v1.HealthResponse
	(*ReadyRequest)(nil),           // 35: garmr.policy.v1.ReadyRequest
	(*ReadyResponse)(nil),          // 36: garmr.policy.v1.ReadyResponse
	nil,                            // 37: garmr.policy.v1.ListPoliciesRequest.LabelsEntry
	nil,                            // 38: garmr.policy.v1.PolicyInfo.LabelsEntry
	nil,                            // 39: garmr.policy.v1.ReadyResponse.ChecksEntry
	(*structpb.Struct)(nil),        // 40: google.protobuf.Struct
	(*structpb.Value)(nil),         // 41: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),  // 42: google.protobuf.Timestamp
}
var file_policy_proto_depIdxs = []int32{
	40, // 0: garmr.policy.v1.EvaluateRequest.input:type_name -> google.protobuf.Struct
	3,  // 1: garmr.policy.v1.EvaluateRequest.options:type_name -> garmr.policy.v1.EvaluateOptions
	0,  // 2: garmr.policy.v1.EvaluateResponse.decision:type_name -> garmr.policy.v1.Decision
	5,  // 3: garmr.policy.v1.EvaluateResponse.results:type_name -> garmr.policy.v1.RuleResult
	7,  // 4: garmr.policy.v1.EvaluateResponse.metrics:type_name -> garmr.policy.v1.Metrics
	8,  // 5: garmr.policy.v1.EvaluateResponse.trace:type_name -> garmr.policy.v1.TraceEvent
	1,  // 6: garmr.policy.v1.RuleResult.severity:type_name -> garmr.policy.v1.Severity
	6,  // 7: garmr.policy.v1.RuleResult.bindings:type_name -> garmr.policy.v1.Binding
	41, // 8: garmr.policy.v1.Binding.value:type_name -> google.protobuf.Value
	42, // 9: garmr.policy.v1.TraceEvent.timestamp:type_name -> google.protobuf.Timestamp
	40, // 10: garmr.policy.v1.TraceEvent.locals:type_name -> google.protobuf.Struct
	11, // 11: garmr.policy.v1.ValidateResponse.errors:type_name -> garmr.policy.v1.ValidationError
	11, // 12: garmr.policy.v1.ValidateResponse.warnings:type_name -> garmr.policy.v1.ValidationError
	12, // 13: garmr.policy.v1.ValidationError.position:type_name -> garmr.policy.v1.Position
	14, // 14: garmr.policy.v1.CompileRequest.policies:type_name -> garmr.policy.v1.PolicySource
	11, // 15: garmr.policy.v1.CompileResponse.errors:type_name -> garmr.policy.v1.ValidationError
	37, // 16: garmr.policy.v1.ListPoliciesRequest.labels:type_name -> garmr.policy.v1.ListPoliciesRequest.LabelsEntry
	18, // 17: garmr.policy.v1.ListPoliciesResponse.policies:type_name -> garmr.policy.v1.PolicyInfo
	38, // 18: garmr.policy.v1.PolicyInfo.labels:type_name -> garmr.policy.v1.PolicyInfo.LabelsEntry
	42, // 19: garmr.policy.v1.PolicyInfo.loaded_at:type_name -> google.protobuf.Timestamp
	18, // 20: garmr.policy.v1.GetPolicyResponse.info:type_name -> garmr.policy.v1.PolicyInfo
	11, // 21: garmr.policy.v1.PutPolicyResponse.errors:type_name -> garmr.policy.v1.ValidationError
	18, // 22: garmr.policy.v1.PutPolicyResponse.info:type_name -> garmr.policy.v1.PolicyInfo
	40, // 23: garmr.policy.v1.PutDataRequest.data:type_name -> google.protobuf.Struct
	40, // 24: garmr.policy.v1.GetDataResponse.data:type_name -> google.protobuf.Struct
	42, // 25: garmr.policy.v1.HealthResponse.uptime:type_name -> google.protobuf.Timestamp
	39, // 26: garmr.policy.v1.ReadyResponse.checks:type_name -> garmr.policy.v1.ReadyResponse.ChecksEntry
	2,  // 27: garmr.policy.v1.PolicyService.Evaluate:input_type -> garmr.policy.v1.EvaluateRequest
	2,  // 28: garmr.policy.v1.PolicyService.EvaluateStream:input_type -> garmr.policy.v1.EvaluateRequest
	9,  // 29: garmr.policy.v1.PolicyService.Validate:input_type -> garmr.policy.v1.ValidateRequest
	13, // 30: garmr.policy.v1.PolicyService.Compile:input_type -> garmr.policy.v1.CompileRequest
	16, // 31: garmr.policy.v1.PolicyManagementService.ListPolicies:input_type -> garmr.policy.v1.ListPoliciesRequest
	19, // 32: garmr.policy.v1.PolicyManagementService.GetPolicy:input_type -> garmr.policy.v1.GetPolicyRequest
	21, // 33: garmr.policy.v1.PolicyManagementService.PutPolicy:input_type -> garmr.policy.v1.PutPolicyRequest
	23, // 34: garmr.policy.v1.PolicyManagementService.DeletePolicy:input_type -> garmr.policy.v1.DeletePolicyRequest
	25, // 35: garmr.policy.v1.PolicyManagementService.ReloadPolicies:input_type -> garmr.policy.v1.ReloadPoliciesRequest
	27, // 36: garmr.policy.v1.DataService.PutData:input_type -> garmr.policy.v1.PutDataRequest
	29, // 37: garmr.policy.v1.DataService.GetData:input_type -> garmr.policy.v1.GetDataRequest
	31, // 38: garmr.policy.v1.DataService.DeleteData:input_type -> garmr.policy.v1.DeleteDataRequest
	33, // 39: garmr.policy.v1.HealthService.Health:input_type -> garmr.policy.v1.HealthRequest
	35, // 40: garmr.policy.v1.HealthService.Ready:input_type -> garmr.policy.v1.ReadyRequest
	4,  // 41: garmr.policy.v1.PolicyService.Evaluate:output_type -> garmr.policy.v1.EvaluateResponse
	4,  // 42: garmr.policy.v1.PolicyService.EvaluateStream:output_type -> garmr.policy.v1.EvaluateResponse
	10, // 43: garmr.policy.v1.PolicyService.Validate:output_type -> garmr.policy.v1.ValidateResponse
	15, // 44: garmr.policy.v1.PolicyService.Compile:output_type -> garmr.policy.v1.CompileResponse
	17, // 45: garmr.policy.v1.PolicyManagementService.ListPolicies:output_type -> garmr.policy.v1.ListPoliciesResponse
	20, // 46: garmr.policy.v1.PolicyManagementService.GetPolicy:output_type -> garmr.policy.v1.GetPolicyResponse
	22, // 47: garmr.policy.v1.PolicyManagementService.PutPolicy:output_type -> garmr.policy.v1.PutPolicyResponse
	24, // 48: garmr.policy.v1.PolicyManagementService.DeletePolicy:output_type -> garmr.policy.v1.DeletePolicyResponse
	26, // 49: garmr.policy.v1.PolicyManagementService.ReloadPolicies:output_type -> garmr.policy.v1.ReloadPoliciesResponse
	28, // 50: garmr.policy.v1.DataService.PutData:output_type -> garmr.policy.v1.PutDataResponse
	30, // 51: garmr.policy.v1.DataService.GetData:output_type -> garmr.policy.v1.GetDataResponse
	32, // 52: garmr.policy.v1.DataService.DeleteData:output_type -> garmr.policy.v1.DeleteDataResponse
	34, // 53: garmr.policy.v1.HealthService.Health:output_type -> garmr.policy.v1.HealthResponse
	36, // 54: garmr.policy.v1.HealthService.Ready:output_type -> garmr.policy.v1.ReadyResponse
	41, // [41:55] is the sub-list for method output_type
	27, // [27:41] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	file_policy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
